
export const reviewFallbacks: Record<number, string[]> = {
  5: [
    "Absolutely phenomenal! The flavors were perfectly balanced and the service was beyond expectations. A true 5-star experience!",
    "Best meal I've had in a long time. Every dish was a masterpiece. Highly recommended!",
    "Exquisite food, amazing atmosphere, and friendly staff. Will definitely be coming back soon!",
    "A culinary journey! The attention to detail in Every plate is remarkable. 5 stars all the way.",
    "Top-tier dining. From the appetizer to the dessert, everything was flawless.",
    "Mind-blowing flavors. I can't stop thinking about that main course. Highly impressive!",
    "The hospitality here makes you feel like royalty. And the food? Simply divine.",
    "A hidden gem! So glad I discovered this place. Everything was 10/10.",
    "Consistent excellence. I've been here three times and it never disappoints.",
    "Beyond perfect. The chef is a genius and the servers are so attentive.",
    "Wonderful evening! Great vibes and even better food. A must-visit!",
    "The plating was like art, and the taste was even better. Pure perfection.",
    "Five stars aren't enough. I'd give it ten if I could. Exceptional!",
    "Incredible variety and fresh ingredients. You can taste the quality in every bite.",
    "Simply the best. No notes. Just go there and experience it for yourself.",
    "A masterclass in gastronomy. Every element was handled with such care.",
    "Fantastic experience! The staff went above and beyond to make our night special.",
    "Delicious from start to finish. The ambiance is perfect for a date night.",
    "So impressed! The creative menu had so many unique and tasty options.",
    "Outstanding! The flavors were bold and authentic. Truly enjoyed it.",
    "The service was fast and the food was hot and delicious. Highly recommend!",
    "Great portions and incredible value for the quality you get. 5/5!",
    "Such a vibrant atmosphere and the food is just soul-satisfying.",
    "A true delight! The chef's recommendations were perfect. I'll be back!",
    "Everything was spot on. The music, the lighting, and the incredible food.",
    "I'm a regular here and it's always fantastic. Best spot in town!",
    "Elegant and delicious. A sophisticated dining experience that stays grounded.",
    "Superb! The fusion of flavors was unexpected and totally successful.",
    "Wow! Just wow! I was blown away by how good everything tasted.",
    "The waitstaff was knowledgeable and the recommendations were perfect. Top shelf!",
    "This place is 100% authentic. The taste took me right back to the roots.",
    "A joy for the senses. Smells great, looks great, and tastes even better.",
    "Loved every second. The service was efficient and very warm.",
    "Simply stunning. The quality of ingredients shines through in every dish.",
    "I'd travel miles for this food. It's that good. Absolutely brilliant experience.",
    "High-end quality without being pretentious. Just great food and great people.",
    "The perfect lunch spot. Quick service but still high-quality food.",
    "A symphony of taste! Every bite was better than the last. Love it!",
    "They really know what they're doing here. Professional and delicious.",
    "If you haven't been here yet, you're missing out. Absolute 5-star perfection.",
    "I've never had a better meal. The flavors are so unique and satisfying.",
    "Exceptional quality and service. They have won a customer for life!",
    "The atmosphere is so cozy and the food is incredibly comforting. 5 stars!",
    "Stellar performance by the kitchen. Everything came out perfectly timed.",
    "A total win! We tried half the menu and loved every single item.",
    "True artistry in the kitchen. The presentation is as good as the flavor.",
    "Warm, welcoming, and wonderfully delicious. What more can you ask for?",
    "Highly creative dishes that actually taste amazing. A rare find!",
    "The best service I've experienced in years. And the food was stellar too.",
    "Magnificent! The dessert alone is worth the trip. High recommendations!"
  ],
  4: [
    "Really good food and solid service. We enjoyed our meal and will be back.",
    "Great experience overall. Just a tiny wait for the table, but the food made up for it.",
    "Very tasty dishes and friendly staff. A solid choice for any day of the week.",
    "Lovely atmosphere and the food was quite good. Enjoyed the variety.",
    "Good quality ingredients and well-prepared meals. Definitely worth a visit.",
    "Impressive menu and the service was prompt. Very happy with our dinner.",
    "Solid 4-star experience. Reliable, tasty, and reasonably priced.",
    "The main course was excellent. The appetizer was good too. Nice spot!",
    "Had a great lunch here. The portions are generous and the flavors are fresh.",
    "Friendly service and consistently good food. One of our favorite go-to places.",
    "Cool vibes and very decent food. I'd definitely recommend it to friends.",
    "The food is definitely the highlight here. Service was okay, but the taste is great.",
    "A very pleasant surprise. Higher quality than I expected. Will return.",
    "Nice decor and the staff was very welcoming. Food was very enjoyable.",
    "Good value for money. Large menu with plenty of appetizing options.",
    "Really enjoyed the flavors. A bit loud, but the food is worth it.",
    "The signature dish is a must-try. Solid quality across the board.",
    "Great for a group dinner. We all found something we liked and the quality was high.",
    "A dependable choice for a good meal. Clean, professional, and tasty.",
    "The staff was very patient and helpful. The food arrived hot and fresh.",
    "Loved the creative twists on classic dishes. Very well executed.",
    "Strong 4 stars. Everything was good - from drinks to the final bite.",
    "Nice ambiance and the appetizers Were standout. Good main courses too.",
    "A very comfortable dining experience with consistently good quality.",
    "I'll be recommending this to my colleagues. Good food and professional service.",
    "The flavors were authentic and well-balanced. A very satisfying meal.",
    "Everything we ordered was cooked to perfection. A very good experience.",
    "The menu has a great range. Everyone found something interesting and tasty.",
    "Consistently high standard. We've never had a bad meal here.",
    "Good atmosphere for a casual Friday night. Food was on point.",
    "A lovely spot with great character. The food is honest and delicious.",
    "Well worth the visit. Diverse menu and very capable kitchen staff.",
    "The portions are huge! You definitely won't leave hungry. Good quality too.",
    "Very nice presentation and the taste was quite refined. 4 stars.",
    "I enjoyed the unique spices used in the dishes. Very flavorful food.",
    "The service was a bit slow, but the food was delicious enough to ignore it.",
    "Solid performance. No major complaints, just a really good meal.",
    "Great spot for a quick but high-quality lunch. I'll be back.",
    "The ingredients seem very fresh. You can tell they care about quality.",
    "Comforting food done right. A very pleasant dining environment.",
    "Nice variety of vegetarian options. Everything we tried was delicious.",
    "The desserts are the secret weapon here. Save room for them!",
    "Good balance of flavors and nice presentation. A very solid choice.",
    "We had a lovely evening. The staff was very attentive and the food was good.",
    "Reliable and tasty. It's exactly what it says on the tin. Good food.",
    "A very positive experience. I'll definitely bring my family here next time.",
    "The atmosphere is very modern and chic. The food matches the vibe well.",
    "I really liked the appetizers. The mains were good too. Solid 4 stars.",
    "Very professional service and clearly skilled chefs. A good dinner.",
    "Happy with my visit. Friendly people and very decent portions."
  ],
  3: [
    "It was okay. Food was decent, but nothing to write home about.",
    "Average experience. The staff was nice, but the food was just standard.",
    "Good enough for a quick bite. Not a destination, but functional.",
    "The atmosphere was nice, but the food felt a bit overpriced for the quality.",
    "An okay lunch. Some hits and some misses on the menu.",
    "Service was friendly, but the food took quite a while to arrive.",
    "Middle of the road. It's fine if you're nearby and hungry.",
    "Decent portions but the flavor was a bit muted. Alright experience.",
    "Not bad, but I've had better in the same price range.",
    "The food was good, but the environment was a bit too noisy for my taste.",
    "An average dining experience. Professional staff but standard food.",
    "It was fine. Nothing was wrong, but nothing was spectacular either.",
    "Okay value. The meal was filling but could have used more seasoning.",
    "Standard fare. If you want a quick, predictable meal, this is the place.",
    "The service was the highlight. The food was just okay.",
    "Fairly decent food. A bit of a wait for the bill at the end.",
    "Acceptable quality. I might come back if I'm in the area.",
    "A functional meal. Good enough to satisfy a hunger, not a craving.",
    "The menu looks better than the delivery. Still, an okay meal.",
    "Nice staff, but the kitchen seemed a bit disorganized today.",
    "It gets the job done. Decent food and an okay atmosphere.",
    "Nothing special, but it's consistent. You know what you're getting.",
    "An average visit. The appetizer was the best part of the whole meal.",
    "Okay for a casual lunch. Wouldn't recommend for a special occasion.",
    "The food was a bit hit or miss. One dish was good, another was bland.",
    "A basic dining experience. Clean place, standard service, okay food.",
    "Fair. I think there's room for improvement in the menu variety.",
    "Just alright. The prices are competitive but the quality is just mid.",
    "Not terrible, but didn't leave a strong impression. 3 stars.",
    "The service was a bit rushed. The food was okay but arrived lukewarm.",
    "It's a fine place for a quick stop. Nothing more, nothing less.",
    "Average flavors. I wish the spices were a bit more authentic.",
    "Service with a smile, but the food was quite unremarkable.",
    "A bit ordinary. I was expecting more based on the reviews.",
    "Adequate. It satisfied my hunger, which was the main goal.",
    "The portions are fine for the price. Quality is middle Tier.",
    "A standard restaurant experience. Reliable but not exciting.",
    "It was a decent meal. I've had better, but I've also had worse.",
    "Nothing to complain about, but nothing to praise either. It's fine.",
    "The ambiance is better than the food. Still an okay experience.",
    "Passable. If you're looking for something quick and easy, it works.",
    "Just your typical diner-style experience. Food is exactly as expected.",
    "The staff is hard-working but the food quality is just average.",
    "Not a bad place, just not very memorable. Okay for a quick lunch.",
    "An okay experience. The main course was a bit underwhelming.",
    "Fair quality. I'll probably try somewhere else next time to compare.",
    "A standard visit. Everything was strictly okay. No more, no less.",
    "The food is fine. The service was a bit distracted. Just average.",
    "Average value for money. It's a safe choice for a quick bite.",
    "An okay meal to end the day. Simple food and standard service."
  ],
  2: [
    "Disappointing experience. The food was bland and the service was slow.",
    "Expected better based on the location. Quality was lacking today.",
    "The order was incorrect and it took a long time to fix. Not great.",
    "The food was cold when it arrived. Very disappointing for the price.",
    "Poor service and mediocre food. Won't be returning anytime soon.",
    "The atmosphere is nice, but that's about it. The meal was a letdown.",
    "Overpriced for what you get. The flavor just wasn't there.",
    "Had higher hopes. The ingredients didn't taste very fresh.",
    "A struggle from start to finish. Long wait times and disappointing food.",
    "The service was quite rude and the food was very oily. 2 stars.",
    "Not a good experience. The menu is limited and the quality is low.",
    "The food was underwhelming and the staff seemed disinterested.",
    "Disappointed with the quality. It felt like a rushed job.",
    "Not worth the price. Small portions and mediocre taste.",
    "I wouldn't recommend this place. Many better options nearby.",
    "The dining area wasn't very clean and the food was just okay.",
    "A frustrating meal. Everything felt like it was done the easy way.",
    "I expected much more flavor. Everything was quite tasteless.",
    "The wait time was unacceptable given how few people were there.",
    "The food just didn't sit right. Quality control needs work.",
    "Subpar experience. Service was the only thing that wasn't bad.",
    "Underwhelming food and noisy environment. Not a relaxing meal.",
    "The staff was overwhelmed and the food suffered for it. Disappointing.",
    "The meal was just not up to standard. Won't be coming back.",
    "Felt like a tourist trap. Overpriced and low quality.",
    "I didn't enjoy the flavors here. Everything felt a bit off.",
    "Poor value for money. I expected better ingredients.",
    "The service was slow and we were mostly ignored by the staff.",
    "The food was quite greasy and didn't taste fresh at all.",
    "A very disappointing lunch. We regretted choosing this spot.",
    "Not a pleasant experience. The atmosphere was stressed and the food was mid.",
    "The presentation was poor and the flavor was even worse.",
    "It took forever to get our order. Not a great way to spend an evening.",
    "The food quality is definitely not what it used to be. Sad to see.",
    "I found the staff to be quite unprofessional. The food was average.",
    "Avoid if you're in a hurry. Slow service and mediocre results.",
    "The portion size was tiny compared to the high price. Not good.",
    "I've had much better versions of these dishes elsewhere.",
    "The seasoning was all wrong. Either too salty or completely bland.",
    "It wasn't a great visit. I'll be looking for other options next time.",
    "The cleanliness of the place was a bit concerning. Food was just okay.",
    "A very underwhelming dinner. We left feeling dissatisfied.",
    "The staff didn't seem to know the menu very well. Frustrating.",
    "The meal was just poorly executed. Many better spots in the area.",
    "I was really hoping for better. A very lackluster experience.",
    "The wait was too long and the food wasn't worth the trouble.",
    "Not a fan. The flavors were weird and the service was lackluster.",
    "I felt like the price didn't match the quality at all. 2 stars.",
    "A poor showing from the kitchen today. Hope they improve.",
    "The overall experience was just below par. Not recommended."
  ],
  1: [
    "Terrible experience. Avoid this place at all costs.",
    "The worst meal I've had in years. Completely inedible.",
    "Rudest staff I've ever encountered. Never coming back.",
    "Horrible service. Waited an hour for food that never came correctly.",
    "Absolute waste of money. Low quality food and terrible atmosphere.",
    "Deeply disappointed. Dirty surroundings and tasteless food.",
    "I wouldn't give this place any stars if I could. Awful experience.",
    "Everything was wrong. From the service to the food quality.",
    "Regretted coming here the moment I stepped in. Truly bad.",
    "The food was cold, greasy, and tasted old. Completely disgusting.",
    "Disastrous evening. They ignored our complaints and were quite rude.",
    "I've never felt more unwelcome in a restaurant. Zero hospitality.",
    "Save your time and money. This place is not worth it.",
    "The quality was shocking. I'm surprised they're still open.",
    "Beyond bad. Unprofessional staff and terrible food execution.",
    "Dirty tables and even worse food. A total nightmare.",
    "Avoid avoid avoid! A complete disaster from start to finish.",
    "The food gave us a stomach ache. Clearly not fresh ingredients.",
    "Worst service ever. We were ignored for 40 minutes.",
    "The meal was a total mess. Seasoning was horrible and it was overcooked.",
    "Not even slightly enjoyable. A frustrating and expensive mistake.",
    "The staff was hostile when we pointed out an issue. Unbelievable.",
    "Everything we ordered was disappointing. Low effort and poor quality.",
    "A complete letdown. Don't believe any positive reviews you see.",
    "The place was filthy and the food was below any standard.",
    "Unpleasant atmosphere and even more unpleasant food. Hard pass.",
    "They really need to rethink their entire operation. It was that bad.",
    "Total lack of care from the staff and the kitchen. Very poor.",
    "Incredibly slow and incredibly bad. A double failure.",
    "I've had better food from a vending machine. Truly awful.",
    "The portion was tiny and the taste was offensive. 1 star.",
    "They got every single thing in our order wrong. Frustrating.",
    "I'm shocked at how bad this was. Zero redemption for this place.",
    "I left after two bites. It was truly that bad. Disappointed.",
    "The prices are a scam for the quality they provide. Avoid.",
    "They were extremely rude to us. No respect for customers at all.",
    "The kitchen seems totally incompetent. A very bad experience.",
    "A total waste of a night out. I wish I had stayed home.",
    "Highly unprofessional. They didn't even apologize for the errors.",
    "The food was burnt and tasteless. How do they even serve this?",
    "A complete disgrace. I wouldn't recommend this to my worst enemy.",
    "The environment was incredibly loud and chaotic. Food was bad too.",
    "It's loud, it's dirty, and the food is terrible. What a combo.",
    "The worst dining experience of my life. Hands down.",
    "Not worth a single cent. I feel robbed after paying for that meal.",
    "They should focus on quality instead of speed. Actually, both failed.",
    "Incredibly rude management. They don't care about their customers.",
    "The food was swimming in grease. I couldn't even finish it.",
    "A miserable experience. I'll make sure to tell everyone to stay away.",
    "Pathetic. That's the only word to describe this place."
  ]
};
